;/*FB_PKG_DELIM*/

__d("CometIXTFacebookAuthenticityWizardTriggerRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="24147021864949694"}),null);
__d("CometIXTFacebookAuthenticityWizardTriggerRootQuery$Parameters",["CometIXTFacebookAuthenticityWizardTriggerRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometIXTFacebookAuthenticityWizardTriggerRootQuery_facebookRelayOperation"),metadata:{},name:"CometIXTFacebookAuthenticityWizardTriggerRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometIXTFacebookAuthenticityWizardTriggerEntryPoint.entrypoint",["CometIXTFacebookAuthenticityWizardTriggerRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","react","uuidv4"],(function(a,b,c,d,e,f,g){"use strict";var h;h||c("react");a={getPreloadProps:function(a){return{queries:{reference:{parameters:c("CometIXTFacebookAuthenticityWizardTriggerRootQuery$Parameters"),variables:{input:babelHelpers["extends"]({},a,{nt_context:null,trigger_session_id:c("uuidv4")()}),scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("CometIXTFacebookAuthenticityWizardTriggerRoot.react").__setRef("CometIXTFacebookAuthenticityWizardTriggerEntryPoint.entrypoint")};b=a;g["default"]=b}),98);
__d("CometIXTMainFacebookAuthenticityWizardTriggerEntryPoint.entrypoint",["cr:7433"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:7433")}),98);
__d("CometIconLogoFlat.react",["cr:11257","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){var c,e=d("react-compiler-runtime").c(3);c=(c=a.color)!=null?c:"fb-logo";var f;e[0]!==a||e[1]!==c?(f=i.jsx(b("cr:11257"),babelHelpers["extends"]({color:c},a)),e[0]=a,e[1]=c,e[2]=f):f=e[2];return f}g["default"]=a}),98);
__d("CometQuickPromotionMenuContext.react",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext();g["default"]=b}),98);
__d("MetaLockupMonochromatic.react",["MetaLockup.react","react","react-compiler-runtime","useCurrentDisplayMode"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){var b=d("react-compiler-runtime").c(3),e=c("useCurrentDisplayMode")();e=e==="dark";e=e?"#fff":"#000";var f;b[0]!==a||b[1]!==e?(f=i.jsx(c("MetaLockup.react"),babelHelpers["extends"]({fill:e},a)),b[0]=a,b[1]=e,b[2]=f):f=b[2];return f}g["default"]=a}),98);
__d("useIXTAuthenticityWizardTriggerDialog",["cr:6468","cr:6554"],(function(a,b,c,d,e,f,g){"use strict";function a(a,c,d){return b("cr:6554")(b("cr:6468"),a,void 0,void 0,{baseModalProps:c,carryOverRelayEnvironment_EXPERIMENTAL:d})}g["default"]=a}),98);